import numpy as np

def field_coil_calc(
    I : float,
    x : np.ndarray,
    p : np.ndarray
) -> np.ndarray:
    '''Caculates the H field of an observer at p from fields generated by lines at x using the Biot Savart Law
        
        Parameters
        ---------- 
        I : float 
            Current (A) in each of the coils
        x : numpy.ndarray shape (num_coils, num_vertices, 3)
            Vertex points of each coil 
        p : numpy.ndarray shape (3,)
            observer point.

        Returns 
        ------- 
        H : numpy.ndarray shape (num_coils,3)
            H field Observed at p due to currents flowing in coils at x

    '''
    
    #DIFFERENCE VECTORS 

    #a is the direction vector of each segment shape (num_coils, num_vertices-1,3)
    a = x[:,1:,:] - x[:,:-1,:]

    #b is the vector from the observer to the end of each segment. Shape (num_coils,num_vertices-1,3)
    #See https://numpy.org/doc/stable/user/basics.broadcasting.html 
    b = x[:,1:,:] - p 

    #c is the direction vector from the observer to the start of each segment. shape(num_coils,num_vertices-1,3)
    c = x[:,:-1,:] - p

    #DOT AND CROSS PRODUCTS 
    #a_dot_b, a_dot_c, mag_b, mag_c, and sq_mag_c_cross_a have shape (num_coils,num_verticies-1)
    #c_cross_a has shape (num_coils, num_vertices -1, 3)
    
    a_dot_b = np.sum(a*b, axis = -1)
    a_dot_c = np.sum(a*c, axis = -1)

    mag_b = np.linalg.norm(b, axis = -1)
    mag_c = np.linalg.norm(c, axis = -1)
    
    c_cross_a = np.cross(c, a, axis = -1)

    sq_mag_c_cross_a = np.sum(c_cross_a * c_cross_a, axis = -1)

    #COMPUTE BIOT SAVART PER SEGMENT (in 3 parts)

    h_1 = (I/(4*np.pi))
    h_2 = c_cross_a / sq_mag_c_cross_a[:,:,np.newaxis]
    h_3 = a_dot_c / mag_c - a_dot_b / mag_b 

    h_per_segment = h_1 * h_2 * h_3[:,:,np.newaxis]

    #SUM OVER THE SEGMENTS TO GET H FOR EACH COIL

    h = np.sum(h_per_segment, axis = 1)

    return h



